name: Raven's Rummager

on:
  schedule:
    - cron: "7 * * * *"
  workflow_dispatch:

jobs:
  rummage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install packages
        run: pip install -r requirements.txt

      - name: Install browser
        run: playwright install --with-deps chromium

      - name: Run Raven's Rummager
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: python bot.py
